module BundleUp
  module Unify
    class Chat < Base
      type chat_user = { id: String, name: String }
      type chat_channel = { id: String, name: String }
      type metadata = { next: String? }

      def users: (?Hash[Symbol, untyped] params) -> { data: Array[chat_user], metadata: metadata }
      def channels: (?Hash[Symbol, untyped] params) -> { data: Array[chat_channel], metadata: metadata }
      def message: (String channel_id, String text) -> { data: Hash[String, untyped] }
    end
  end
end
