module BundleUp
  module Unify
    class Ticketing < Base
      type ticketing_ticket = {
        id: String,
        title: String,
        status: String,
        url: String,
        description: String?,
        created_at: String,
        updated_at: String
      }

      type ticket = {
        id: String,
        title: String,
        status: String?,
        url: String?,
        description: String?,
        created_at: String?,
        updated_at: String?
      }

      type metadata = { next: String? }

      def tickets: (?Hash[Symbol, untyped] params) -> { data: Array[ticketing_ticket], metadata: metadata }

      def ticket: (String ticket_id, ?Hash[Symbol, untyped] params) -> { data: ticket }

      private

      def blank?: (untyped) -> bool
    end
  end
end
